'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("lab3.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blue_bg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blue_bg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hangman_1_arm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hangman_1_arm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hangman_1_leg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hangman_1_leg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hangman_2_arms() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hangman_2_arms", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hangman_body() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hangman_body", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hangman_empty() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hangman_empty", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hangman_head() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hangman_head", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hangman_over() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hangman_over", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hangman_string() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hangman_string", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hangman_whole() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hangman_whole", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property petals() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("petals", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property scrabble_bg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scrabble_bg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property subtle1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("subtle1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to aardvark
        '''aardwolf
        '''aaron
        '''aback
        '''abacus
        '''abaft
        '''abalone
        '''abandon
        '''abandoned
        '''abandonment
        '''abandons
        '''abase
        '''abased
        '''abasement
        '''abash
        '''abashed
        '''abate
        '''abated
        '''abatement
        '''abates
        '''abattoir
        '''abattoirs
        '''abbe
        '''abbess
        '''abbey
        '''abbeys
        '''abbot
        '''abbots
        '''abbreviate
        '''abbreviated
        '''abbreviates
        '''abbreviating
        '''abbreviation
        '''abbreviations
        '''abdicate
        '''abdicated
        '''abdicates
        '''abdicating
        '''abdication
        '''abdomen
        '''abdomens
        '''abdominal
        '''abduct
        '''abducted
        '''abducting
        '''abduction
        '''abductions
        '''abductor
        '''abductors
        '''abducts
        '''abe
        '''abeam
        '''abel
        '''abe [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property words() As String
            Get
                Return ResourceManager.GetString("words", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
